// @ts-nocheck
'use client';

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/navigation';
import { useProjectStore } from '@/stores/project-store';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { Label } from '@/components/ui/label';
import { Loader2, Plus, Trash2, Sparkles, Check } from 'lucide-react';
import { useState } from 'react';

const API = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000';

type Attribute = { name: string; type: string; required: boolean; unique: boolean; notes: string };
type Entity = { name: string; description: string; attributes: Attribute[] };
type Relationship = { name: string; type: 'one-to-one' | 'one-to-many' | 'many-to-many'; source: string; target: string; description: string };
type Index = { name: string; entity: string; columns: string[]; unique: boolean };

type DataModelData = {
  entities: Entity[];
  relationships: Relationship[];
  indexes: Index[];
  notes: string;
};

const emptyData: DataModelData = {
  entities: [],
  relationships: [],
  indexes: [],
  notes: '',
};

async function fetchDataModel(projectId: string, token: string) {
  const res = await fetch(`${API}/api/v1/projects/${projectId}/data`, {
    headers: { Authorization: `Bearer ${token}` },
  });
  const json = await res.json();
  return json.data ?? null;
}

async function saveDataModel(projectId: string, token: string, data: DataModelData) {
  const res = await fetch(`${API}/api/v1/projects/${projectId}/data`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
    body: JSON.stringify(data),
  });
  const json = await res.json();
  if (!json.success) throw new Error(json.error);
  return json.data;
}

type Props = { projectId: string };

export function DataModeller({ projectId }: Props) {
  const { data: session } = useSession();
  const router = useRouter();
  const { setCurrentPhase } = useProjectStore();
  const token = (session?.user as any)?.accessToken;
  const queryClient = useQueryClient();

  const { data, isLoading } = useQuery({
    queryKey: ['data-model', projectId],
    queryFn: () => fetchDataModel(projectId, token),
    enabled: !!token,
  });

  const [local, setLocal] = useState<DataModelData | null>(null);
  const form = local ?? data ?? emptyData;

  const saveMutation = useMutation({
    mutationFn: (d: DataModelData) => saveDataModel(projectId, token, d),
    onSuccess: () => {
      toast.success('Data model saved');
      queryClient.invalidateQueries({ queryKey: ['data-model', projectId] });
    },
    onError: (err: Error) => toast.error(err.message),
  });

  const generateMutation = useMutation({
    mutationFn: async () => {
      const res = await fetch(`${API}/api/v1/projects/${projectId}/data/generate`, {
        method: 'POST',
        headers: { Authorization: `Bearer ${token}` },
      });
      const json = await res.json();
      if (!json.success) throw new Error(json.error);
      return json.data;
    },
    onSuccess: (generatedData) => {
      toast.success('Data model generated by AI!');
      setLocal(generatedData);
    },
    onError: (err: Error) => toast.error(err.message),
  });

  const completeMutation = useMutation({
    mutationFn: async () => {
      const res = await fetch(`${API}/api/v1/projects/${projectId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
        body: JSON.stringify({ currentPhase: 5 }),
      });
      const json = await res.json();
      if (!json.success) throw new Error(json.error);
      return json.data;
    },
    onSuccess: () => {
      toast.success('Data model phase completed!');
      setCurrentPhase(5);
      queryClient.invalidateQueries({ queryKey: ['project', projectId] });
      router.push(`/projects/${projectId}/security`);
    },
    onError: (err: Error) => toast.error(err.message),
  });

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  const update = (patch: Partial<DataModelData>) => setLocal({ ...form, ...patch });

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <p className="text-sm text-muted-foreground">Define entities, attributes, and relationships for your data model.</p>
        <div className="flex gap-2">
          <Button
            variant="outline"
            onClick={() => generateMutation.mutate()}
            disabled={generateMutation.isPending}
            className="bg-gradient-to-r from-indigo-500/10 to-purple-500/10 hover:from-indigo-500/20 hover:to-purple-500/20 border-indigo-500/20"
          >
            {generateMutation.isPending ? (
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            ) : (
              <Sparkles className="mr-2 h-4 w-4 text-indigo-500" />
            )}
            Generate with AI
          </Button>
          <Button onClick={() => saveMutation.mutate(form)} disabled={saveMutation.isPending}>
            {saveMutation.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
            Save Data Model
          </Button>
          <Button
            variant="default"
            className="bg-emerald-600 hover:bg-emerald-700 text-white"
            onClick={() => completeMutation.mutate()}
            disabled={completeMutation.isPending}
          >
            {completeMutation.isPending ? (
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            ) : (
              <Check className="mr-2 h-4 w-4" />
            )}
            Complete Phase 4
          </Button>
        </div>
      </div>

      <Card>
        <CardHeader className="flex flex-row items-center justify-between">
          <CardTitle className="text-base">Entities</CardTitle>
          <Button
            variant="outline"
            size="sm"
            onClick={() =>
              update({
                entities: [...(form.entities || []), { name: '', description: '', attributes: [] }],
              })
            }
          >
            <Plus className="h-4 w-4 mr-1" /> Add Entity
          </Button>
        </CardHeader>
        <CardContent className="space-y-6">
          {(form.entities || []).map((ent, ei) => (
            <div key={ei} className="space-y-4 p-4 border rounded-lg relative group">
              <Button
                variant="ghost"
                size="icon"
                className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity"
                onClick={() => update({ entities: form.entities.filter((_, i) => i !== ei) })}
              >
                <Trash2 className="h-4 w-4" />
              </Button>

              <div className="flex gap-4">
                <div className="flex-1 space-y-2">
                  <Label>Entity Name</Label>
                  <Input
                    value={ent.name}
                    onChange={(e) => {
                      const u = [...form.entities];
                      u[ei] = { ...u[ei], name: e.target.value };
                      update({ entities: u });
                    }}
                    placeholder="User, Product, Order..."
                  />
                </div>
              </div>

              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <Label className="text-xs font-semibold uppercase text-muted-foreground">Attributes</Label>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => {
                      const u = [...form.entities];
                      u[ei] = {
                        ...u[ei],
                        attributes: [...(ent.attributes || []), { name: '', type: 'string', required: true, unique: false }],
                      };
                      update({ entities: u });
                    }}
                  >
                    <Plus className="h-3 w-3 mr-1" /> Add Attribute
                  </Button>
                </div>

                <div className="grid gap-2">
                  {(ent.attributes || []).map((attr, ai) => (
                    <div key={ai} className="flex items-center gap-2">
                      <Input
                        placeholder="Name"
                        value={attr.name}
                        onChange={(e) => {
                          const u = [...form.entities];
                          const a = [...(u[ei].attributes || [])];
                          a[ai] = { ...a[ai], name: e.target.value };
                          u[ei] = { ...u[ei], attributes: a };
                          update({ entities: u });
                        }}
                        className="h-8 flex-1"
                      />
                      <Select
                        value={attr.type}
                        onValueChange={(v) => {
                          const u = [...form.entities];
                          const a = [...(u[ei].attributes || [])];
                          a[ai] = { ...a[ai], type: v };
                          u[ei] = { ...u[ei], attributes: a };
                          update({ entities: u });
                        }}
                      >
                        <SelectTrigger className="h-8 w-28 text-xs">
                          <SelectValue placeholder="Type" />
                        </SelectTrigger>
                        <SelectContent>
                          {['string', 'number', 'boolean', 'date', 'uuid', 'json', 'text'].map((t) => (
                            <SelectItem key={t} value={t} className="text-xs">
                              {t}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      <div className="flex items-center gap-2 px-2 border rounded h-8 bg-muted/30">
                        <div className="flex items-center gap-1">
                          <Checkbox
                            id={`req-${ei}-${ai}`}
                            checked={attr.required}
                            onCheckedChange={(v) => {
                              const u = [...form.entities];
                              const a = [...(u[ei].attributes || [])];
                              a[ai] = { ...a[ai], required: !!v };
                              u[ei] = { ...u[ei], attributes: a };
                              update({ entities: u });
                            }}
                          />
                          <Label htmlFor={`req-${ei}-${ai}`} className="text-[10px] uppercase font-bold">Req</Label>
                        </div>
                        <div className="flex items-center gap-1">
                          <Checkbox
                            id={`unq-${ei}-${ai}`}
                            checked={attr.unique}
                            onCheckedChange={(v) => {
                              const u = [...form.entities];
                              const a = [...(u[ei].attributes || [])];
                              a[ai] = { ...a[ai], unique: !!v };
                              u[ei] = { ...u[ei], attributes: a };
                              update({ entities: u });
                            }}
                          />
                          <Label htmlFor={`unq-${ei}-${ai}`} className="text-[10px] uppercase font-bold">Unq</Label>
                        </div>
                      </div>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-8 w-8 text-destructive"
                        onClick={() => {
                          const u = [...form.entities];
                          const a = (u[ei].attributes || []).filter((_, i) => i !== ai);
                          u[ei] = { ...u[ei], attributes: a };
                          update({ entities: u });
                        }}
                      >
                        <Trash2 className="h-4 w-4" />
                      </Button>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          ))}
        </CardContent>
      </Card>

      <Card>
        <CardHeader className="flex flex-row items-center justify-between">
          <CardTitle className="text-base">Relationships</CardTitle>
          <Button variant="outline" size="sm" onClick={() => update({ relationships: [...form.relationships, { name: '', type: 'one-to-many', source: '', target: '', description: '' }] })}>
            <Plus className="h-4 w-4 mr-1" /> Add Relationship
          </Button>
        </CardHeader>
        <CardContent className="space-y-3">
          {(form.relationships || []).map((rel, ri) => (
            <div key={ri} className="border rounded-lg p-3 flex items-start gap-3">
              <div className="flex-1 space-y-2">
                <Input
                  placeholder="Relationship name"
                  value={rel.name}
                  onChange={(e) => {
                    const u = [...form.relationships];
                    u[ri] = { ...u[ri], name: e.target.value };
                    update({ relationships: u });
                  }}
                />
                <div className="flex gap-2">
                  <Input
                    placeholder="Source entity"
                    value={rel.source}
                    onChange={(e) => {
                      const u = [...form.relationships];
                      u[ri] = { ...u[ri], source: e.target.value };
                      update({ relationships: u });
                    }}
                  />
                  <Select
                    value={rel.type}
                    onValueChange={(v: 'one-to-one' | 'one-to-many' | 'many-to-many') => {
                      const u = [...form.relationships];
                      u[ri] = { ...u[ri], type: v };
                      update({ relationships: u });
                    }}
                  >
                    <SelectTrigger className="w-36"><SelectValue /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="one-to-one">1:1</SelectItem>
                      <SelectItem value="one-to-many">1:N</SelectItem>
                      <SelectItem value="many-to-many">M:N</SelectItem>
                    </SelectContent>
                  </Select>
                  <Input
                    placeholder="Target entity"
                    value={rel.target}
                    onChange={(e) => {
                      const u = [...form.relationships];
                      u[ri] = { ...u[ri], target: e.target.value };
                      update({ relationships: u });
                    }}
                  />
                </div>
              </div>
              <Button variant="ghost" size="icon" onClick={() => update({ relationships: form.relationships.filter((_, i) => i !== ri) })}>
                <Trash2 className="h-4 w-4" />
              </Button>
            </div>
          ))}
        </CardContent>
      </Card>

      <Card>
        <CardHeader className="flex flex-row items-center justify-between">
          <CardTitle className="text-base">Indexes</CardTitle>
          <Button variant="outline" size="sm" onClick={() => update({ indexes: [...form.indexes, { name: '', entity: '', columns: [], unique: false }] })}>
            <Plus className="h-4 w-4 mr-1" /> Add Index
          </Button>
        </CardHeader>
        <CardContent className="space-y-3">
          {(form.indexes || []).map((idx, ii) => (
            <div key={ii} className="border rounded-lg p-3 flex items-center gap-3">
              <Input
                placeholder="Index name"
                value={idx.name}
                onChange={(e) => {
                  const u = [...form.indexes];
                  u[ii] = { ...u[ii], name: e.target.value };
                  update({ indexes: u });
                }}
                className="w-48"
              />
              <Input
                placeholder="Entity"
                value={idx.entity}
                onChange={(e) => {
                  const u = [...form.indexes];
                  u[ii] = { ...u[ii], entity: e.target.value };
                  update({ indexes: u });
                }}
                className="w-36"
              />
              <Input
                placeholder="Columns (comma-separated)"
                value={(idx.columns || idx.fields || []).join(', ')}
                onChange={(e) => {
                  const u = [...form.indexes];
                  const cols = e.target.value.split(',').map((s) => s.trim()).filter(Boolean);
                  u[ii] = { ...u[ii], columns: cols, fields: cols };
                  update({ indexes: u });
                }}
                className="flex-1"
              />
              <div className="flex items-center gap-1 text-xs text-muted-foreground shrink-0">
                <Checkbox
                  checked={idx.unique}
                  onCheckedChange={(v) => {
                    const u = [...form.indexes];
                    u[ii] = { ...u[ii], unique: !!v };
                    update({ indexes: u });
                  }}
                />
                <span>Unique</span>
              </div>
              <Button variant="ghost" size="icon" onClick={() => update({ indexes: form.indexes.filter((_, i) => i !== ii) })}>
                <Trash2 className="h-4 w-4" />
              </Button>
            </div>
          ))}
        </CardContent>
      </Card>

      <Card>
        <CardHeader><CardTitle className="text-base">Notes</CardTitle></CardHeader>
        <CardContent>
          <Textarea
            placeholder="Additional notes about the data model..."
            value={form.notes || ''}
            onChange={(e) => update({ notes: e.target.value })}
            rows={4}
          />
        </CardContent>
      </Card>
    </div>
  );
}
